---
- name: Install docker-compose.yml 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "ec2-user"
    group: "ec2-user"
  with_items:
    - { src: "docker-compose.yml.j2", dest: "{{ default_dir }}/docker-compose.yml", mode: "0644" }

- name: Install Gitlab
  docker_compose:
    project_name: gitlab
    project_src: "{{ default_dir }}"
    pull: yes
    state: present
  register: outputGitlab