---
- name: Install Docker, Gitlab Packages
  hosts: all
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  roles:
    - { role: volume, tags: [ 'all', 'volume' ] }
    - { role: docker, tags: [ 'all', 'docker' ] }
    - { role: gitlab, tags: [ 'all', 'gitlab' ] }
    - { role: backup, tags: [ 'all', 'backup' ] }
    - { role: upgrade, tags: [ 'all', 'upgrade' ] }
