---
- name: Backup Gitlab data
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    argv:
      - /bin/bash
      - -c
      - "gitlab-backup create"
  register: bckGitlab