---
- name: Backup Gitlab data
  docker_container:
    project_name: gitlab
    project_src: "{{ default_dir }}"
    pull: yes
    state: present
  register: gitlab_output

#- name: Remove Gitlab
#  docker_compose:
#    project_src: "{{ default_dir }}"
#    state: absent
#    remove_volumes: yes
#  register: absent_output
